#ifndef _DBGPRINTCUSTOM_H_
#define _DBGPRINTCUSTOM_H_

#define MODULES(f)	\
	f(MAIN,			ALL,	TRACE,	ALL,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_BLACK)	\
	f(DBGMENU,		ALL,	TRACE,	WARN,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_BLACK)	\
	f(RFD,			ALL,	INFO,	WARN,	DBG_TERMINAL_COLOR_GREEN,	DBG_TERMINAL_COLOR_BLACK)	\
	f(RFL,			ALL,	INFO,	WARN,	DBG_TERMINAL_COLOR_MAGENTA,	DBG_TERMINAL_COLOR_BLACK)	\
	f(BLE,			ALL,	TRACE,	WARN,	DBG_TERMINAL_COLOR_BLUE,	DBG_TERMINAL_COLOR_BLACK)	\
	f(DEX,			ALL,	TRACE,	WARN,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_BLACK)	\
	f(FG,			ALL,	TRACE,	WARN,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_BLACK)	\
	f(EPROM,		ALL,	TRACE,	WARN,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_BLACK)	\
	f(UART,			ALL,	TRACE,	WARN,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_BLACK)	\
	f(I2C,			ALL,	TRACE,	WARN,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_BLACK)	\
	f(FXL6408,		ALL,	TRACE,	WARN,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_BLACK)	\
	f(STC3115,		ALL,	INFO,	WARN,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_BLACK)	\
	f(GSM,			ALL,	TRACE,	WARN,	DBG_TERMINAL_COLOR_GREEN,	DBG_TERMINAL_COLOR_BLACK)	\
	f(CRYPT,		ALL,	TRACE,	WARN,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_BLACK)	\
	f(SERVICES,		ALL,	TRACE,	ALL,	DBG_TERMINAL_COLOR_GREEN,	DBG_TERMINAL_COLOR_BLACK)	\
	f(CLK,			ALL,	TRACE,	ALL,	DBG_TERMINAL_COLOR_GREEN,	DBG_TERMINAL_COLOR_BLACK)	\
	f(PERSIST,		ALL,	TRACE,	ALL,	DBG_TERMINAL_COLOR_GREEN,	DBG_TERMINAL_COLOR_BLACK)	\
	f(FIFO,			ALL,	TRACE,	ALL,	DBG_TERMINAL_COLOR_GREEN,	DBG_TERMINAL_COLOR_BLACK)	\
	f(CACHE,		ALL,	TRACE,	ALL,	DBG_TERMINAL_COLOR_GREEN,	DBG_TERMINAL_COLOR_BLACK)	\
	f(VER,			ALL,	TRACE,	ALL,	DBG_TERMINAL_COLOR_GREEN,	DBG_TERMINAL_COLOR_BLACK)	\
	f(ASSERT,		ALL,	ALL,	ERROR,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_BLACK)	\
	f(LAST,			NONE,	NONE,	NONE,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_BLACK)

		
#define WARN_PIN(buf)		WARN_BUF("pin: ",	PRINT_BUF_STYLE_HEX_NL,	(buf),	PIN_LEN);
#define WARN_USER(buf)		WARN_BUF("userId: ",PRINT_BUF_STYLE_ASC_NL,	(buf),	USER_ID_LEN);
#define WARN_APP(buf)		WARN_BUF("appId: ",	PRINT_BUF_STYLE_HEX_NL,	(buf),	APP_ID_LEN);
#define WARN_KEY(buf)		WARN_BUF("key",		PRINT_BUF_STYLE_HEX_NL,	(buf),	DOOR_KEY_LEN);
#define WARN_AES(pref, buf)	WARN_BUF((pref),	PRINT_BUF_STYLE_HEX_NL,	(buf),	AES_BLOCK_SIZE);
#define WARN_PUB(pref, buf)	WARN_BUF((pref),	PRINT_BUF_STYLE_HEX_NL,	(buf),	PUBLIC_KEY_LEN+1);

#define INFO_PIN(buf)		INFO_BUF("pin: ",		PRINT_BUF_STYLE_ASC_NL,	(buf),	PIN_LEN);
#define INFO_USER(buf)		INFO_BUF("userId: ",	PRINT_BUF_STYLE_HEX_NL,	(buf),	USER_ID_LEN);
#define INFO_APP(buf)		INFO_BUF("appId: ",		PRINT_BUF_STYLE_HEX_NL,	(buf),	APP_ID_LEN);
#define INFO_KEY(buf)		INFO_BUF("key",			PRINT_BUF_STYLE_HEX_NL,	(buf),	DOOR_KEY_LEN);
#define INFO_AES(pref, buf)	INFO_BUF((pref),		PRINT_BUF_STYLE_HEX_NL,	(buf),	AES_BLOCK_SIZE);
#define INFO_PUB(pref, buf)	INFO_BUF((pref),		PRINT_BUF_STYLE_HEX_NL,	(buf),	PUBLIC_KEY_LEN+1);

#define TRACE_PIN(buf)			TRACE_BUF("pin: ",		PRINT_BUF_STYLE_ASC_NL,	(buf),	PIN_LEN);
#define TRACE_USER(buf)			TRACE_BUF("userId: ",	PRINT_BUF_STYLE_ASC_NL,	(buf),	USER_ID_LEN);
#define TRACE_APP(buf)			TRACE_BUF("appId: ",	PRINT_BUF_STYLE_ASC_NL,	(buf),	APP_ID_LEN);
#define TRACE_KEY(buf)			TRACE_BUF("key",		PRINT_BUF_STYLE_HEX_NL,	(buf),	DOOR_KEY_LEN);
#define TRACE_AES(pref, buf)	TRACE_BUF((pref),		PRINT_BUF_STYLE_HEX_NL,	(buf),	AES_BLOCK_SIZE);
#define TRACE_PUB(pref, buf)	TRACE_BUF((pref),		PRINT_BUF_STYLE_HEX_NL,	(buf),	PUBLIC_KEY_LEN+1);

		
#endif // _DBGPRINTCUSTOM_H_

